In [2]:
import pandas as pd
import json

# Load the JSON file
with open('datasets/ami/annotations/train.json') as f:
    data = json.load(f)

# Create a pandas DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
df.head()

,meeting_id,time_pairs,speaker_id,text
0,EN2001a,"[[3.3399999141693115, 3.880000114440918], [5.5...","[MEO069, MEE068, MEO069, MEO069, MEE068, MEO06...","['KAY, OKAY, GOSH, 'KAY, DOES ANYONE WANT TO S..."
1,EN2001b,"[[3.0899999141693115, 3.240000009536743], [22....","[FEO066, FEO065, FEO066, MEO069, FEO066, MEO06...","[HMM, YEAH, IT'S WITH CAMERAS, HMM, YOU LOOK Q..."
2,EN2001d,"[[20.84000015258789, 21.329999923706055], [37....","[FEO066, MEO069, MEO069, MEE067, MEE068, MEO06...","[AH YEAH, OKAY, OKAY, OKAY, YEP, OKAY, DID I T..."
3,EN2001e,"[[0.019999999552965164, 1.0800000429153442], [...","[MEE067, MEO069, FEO066, MEO069, MEO069, MEO06...","[SIXTEEN TIMES ZERO, I'M NOT A HUNDRED PERCENT..."
4,EN2003a,"[[14.40999984741211, 16.360000610351562], [16....","[MEO074, MEE075, MEO074, MEE075, MEE075, MEE07...","[MM-HMM, MM-HMM, CAN YOU JUST REMIND ME I DON'..."

In [3]:
time_pairs=df[df["meeting_id"]=="EN2001a"]["time_pairs"]

In [4]:
len(time_pairs.to_list()[0])

1168

In [5]:
from datasets import load_dataset

ds = load_dataset("edinburghcstr/ami", "ihm", split="train", trust_remote_code=True)

/home/michele/anaconda3/envs/DL4NLP_yolo/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [6]:
ds.to_pandas().sort_values(["meeting_id","begin_time","end_time"])

,meeting_id,audio_id,text,audio,begin_time,end_time,microphone_id,speaker_id
299,EN2001a,AMI_EN2001a_H04_MEO069_0000334_0000388,'KAY,"{'bytes': None, 'path': '/home/michele/.cache/...",3.340000,3.880000,H04,MEO069
1591,EN2001a,AMI_EN2001a_H00_MEE068_0000557_0000594,OKAY,"{'bytes': None, 'path': '/home/michele/.cache/...",5.570000,5.940000,H00,MEE068
47,EN2001a,AMI_EN2001a_H04_MEO069_0000560_0000601,GOSH,"{'bytes': None, 'path': '/home/michele/.cache/...",5.600000,6.010000,H04,MEO069
794,EN2001a,AMI_EN2001a_H04_MEO069_0001048_0001088,'KAY,"{'bytes': None, 'path': '/home/michele/.cache/...",10.480000,10.880000,H04,MEO069
1266,EN2001a,AMI_EN2001a_H00_MEE068_0001109_0001553,DOES ANYONE WANT TO SEE UH STEVE'S FEEDBACK FR...,"{'bytes': None, 'path': '/home/michele/.cache/...",11.090000,15.530000,H00,MEE068
...,...,...,...,...,...,...,...,...
108457,TS3012d,AMI_TS3012d_H03_MTD048ME_0230011_0230278,OKAY THEN WE'LL OVERALL TWO POINTS,"{'bytes': None, 'path': '/home/michele/.cache/...",2300.110107,2302.780029,H03,MTD048ME
107441,TS3012d,AMI_TS3012d_H03_MTD048ME_0230278_0230313,YES,"{'bytes': None, 'path': '/home/michele/.cache/...",2302.780029,2303.129883,H03,MTD048ME
108257,TS3012d,AMI_TS3012d_H01_MTD047UID_0230689_0230765,I SEE YOU LATER,"{'bytes': None, 'path': '/home/michele/.cache/...",2306.889893,2307.649902,H01,MTD047UID
107651,TS3012d,AMI_TS3012d_H03_MTD048ME_0230804_0230825,YEAH,"{'bytes': None, 'path': '/home/michele/.cache/...",2308.040039,2308.250000,H03,MTD048ME
108263,TS3012d,AMI_TS3012d_H03_MTD048ME_0232390_0232439,MM,"{'bytes': None, 'path': '/home/michele/.cache/...",2323.899902,2324.389893,H03,MTD048ME